image: gitlab/dind

services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/portfolio .
    - docker-compose -f docker-compose.yml up -d --build
