image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/portfolio .
    - docker run -d --name portfolio --expose 80 --net nginx-proxy -e VIRTUAL_HOST=blog.DOMAIN.TLD app/portfolio
