image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - deploy

step-deploy-prod:
  stage: deploy
  script:
    - docker build -t portfolio .
    - docker-compose -f docker-compose.yml up -d --build
