image: docker:19.03.12

services:
  - docker:19.03.12-dind

stages:
  - deploy

step-deploy-prod:
  stage: deploy
  before_script:
    - docker info
  script:
    - docker-compose -f docker-compose.yml up -d --build
